# Generated by Django 4.2.13 on 2024-06-30 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_address", models.CharField(max_length=256)),
                ("receiver_address", models.CharField(max_length=256)),
                ("amount", models.FloatField()),
                ("payment_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INPROGRESS", "INPROGRESS"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("SCHEDULED", "SCHEDULED"), ("LOCKED", "LOCKED")],
                        max_length=256,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "payments",
                "db_table": "payment",
                "ordering": ["-payment_datetime"],
            },
        ),
    ]
